# Site settings
title: Penapalooza
email: john.pena+nospam@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    I'm the bassist and backup drummer for the band Mr. This. 
    In my free time I work as a programmer for Twitter. I'm not available for hire.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://penapalooza.com" # the base hostname & protocol for your site
twitter_username: pena
github_username:  johnpena

# Build settings
markdown: kramdown
